services:
  express:
    build:
      context: .
      dockerfile: Dockerfile  # Express Dockerfile
    ports:
      - "3000:3000"
    networks:
      - orm-network

  nginx:
    image: nginx:alpine
    volumes:
      - /home/ubuntu/nginx.config:/etc/nginx/conf.d/default.conf  # Nginx 설정 파일 경로
    ports:
      - "80:80"
    depends_on:
      - express
    networks:
      - orm-network

networks:
  orm-network:
    driver: bridge
